apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "prophet-collector.fullname" . }}
  labels:
    {{- include "prophet-collector.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "prophet-collector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "prophet-collector.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: collector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            capabilities:
              add:
                - NET_RAW
                - NET_ADMIN
          command: ["./collector"]
          args:
            - "--provision-token=$(PROVISION_TOKEN)"
            - "--environment={{ .Values.env }}"
            - "--dynamic_node"
            - "--hostname=$(NODE_NAME)"
            {{- if .Values.profileId }}
            - "--profile_id={{ .Values.profileId }}"
            {{- end }}
          env:
            - name: PROVISION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "prophet-collector.fullname" . }}
                  key: provision-token
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: prophet-state
              mountPath: /usr/local/prophet
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: prophet-state
          hostPath:
            path: {{ .Values.persistence.hostPath | default "/var/lib/prophet-collector" }}
            type: DirectoryOrCreate
